kind: Model
apiVersion: v1alpha5
metadata:
  displayName: Spatial data transformer
  type: data-processing
  name: spatial-data-transformer
  summary: A utility tool for transforming spatial data
  description: >
    Enables spatial data transformations using gdal methods. Supports a range of methods for both vector and raster data types.
spec:
  inputs:
    env:
      - name: process
        title: Process(transform) function
        type: string
        description: The type of process to perform e.g clip, re-project
        default: re-project
        required: true
        options:
          - name: clip
            title: Clip a spatial dataset
          - name: re-project
            title: Re-project into another coordinate system

      - name: data_type
        title: Data type
        type: string
        description: The data format to be transformed
        default: vector
        required: false
        options:
          - name: vector
            title: Vector format data
          - name: raster
            title: Raster format datas

      - name: output_crs
        title: The CRS for the re-projected dataset
        description: Required whe using the re-project transform function. Should be a valid EPSG code e.g. 27700 (BNG), 4326 (GPS CRS)
        type: string
        default: '27700'
        required: false

      - name: input_file
        title: Input clip file
        description: The name of the file passed to be clipped. Required only when running the clip transform.
        type: string
        default: ''
        required: false

      - name: clip_file
        title: Input boundary clip file
        description: The name of the file passed to be used to clip the input_file. Required only when running the clip transform.
        type: string
        default: ''
        required: false

      - name: output_file
        title: Output file name
        description: The name to be given to the output file. Required only when running the clip transform.
        type: string
        required: false
        default: ''

      - name: extent
        title: extent
        type: string
        description: Should be formatted as `<xmin>,<ymin>,<xmax>,<ymax>`
        default: ''
        required: false

    dataslots:
      - name: Input data files
        description: Any input data files for the processing transforms to be run.
        path: inputs/
        required: false

  outputs:
    datasets:
      - name: outputs/run/**/*
        type: folder
        description: path to processed data outputs
